services:
  - type: web
    name: bitcoin-notifications-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    branch: main  # Change if you're using a different branch
    repo: https://github.com/mohitkesarwani/Bitcoin-notifications
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
    autoDeploy: true
    healthCheckPath: /health
    buildFilter:
      paths:
        - "routes/**"
        - "tests/**"
        - "index.js"
        - "package.json"
        - ".env.example"
