services:
  - type: web
    name: bitcoin-notification-api
    env: node
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: TWELVE_DATA_API_KEY
        sync: false
