services:
  - type: web
    name: bitcoin-notification-api
    rootDir: api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TWELVE_DATA_API_KEY
        sync: false

  - type: web
    name: bitcoin-dashboard
    rootDir: client
    env: static
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
